name: "pint action"
description: "Validate Prometheus rules using cloudflare/pint"
branding:
  color: orange
  icon: bell
inputs:
  token:
    description: "Github token to use"
    required: true
  workdir:
    description: "Working directory to use"
    required: false
    default: "."
  config:
    description: "Config file to use"
    required: false
    default: ""
  loglevel:
    description: "Log level to use"
    required: false
    default: ""
  minSeverity:
    description: "Minimum severity to report"
    required: false
    default: ""
  requireOwner:
    description: "Require all rules to have an owner set via comment"
    required: false
    default: ""
    
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_AUTH_TOKEN: ${{ inputs.token }}
    CONFIG: ${{ inputs.config }}
    WORKDIR: ${{ inputs.workdir }}
    LOGLEVEL: ${{ inputs.loglevel }}
    MIN_SEVERITY: ${{ inputs.minSeverity }}
    REQUIRE_OWNER: ${{ inputs.requireOwner }}
    PULL_REQUEST_TARGET_REPO: ${{ github.event.pull_request.base.repo.full_name }}
    PULL_REQUEST_SOURCE_REPO: ${{ github.event.pull_request.head.repo.full_name }}
